### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by zhenghanzheng** [Cuadrix/puppeteer-page-proxy#11]
(node:9924) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at assert (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\helper.js:283:11)
    at Request.abort (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\NetworkManager.js:495:5)
    at Request.<anonymous> (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\helper.js:112:23)
    at Page.$puppeteerPageProxyHandler (D:\code\diandog\diandogbrowser\node_modules\puppeteer-page-proxy\src\core\page-proxy.js:36:23)
(node:9924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zhenghanzheng** [comment]
"puppeteer-core": "^2.0.0",

**Comment by zhenghanzheng** [comment]
Error: RequestError: Cannot read property 'startsWith' of undefined
    at request (D:\code\diandog\diandogbrowser\node_modules\puppeteer-page-proxy\src\lib\request.js:43:19)

**Comment by Bouzazi** [comment]
Had this error.
If you're intercepting requests, make sure you do it like this
```
await page.setRequestInterception(true);
page.on('request', req => {
    if (req.resourceType() === 'image') {
        req.abort();
    } else {
        useProxy(req, proxy);
    }
});
```
