### ISSUE TITLE
Error: connect ECONNRESET 127.0.0.1:59033

### ISSUE THREAD

**Issue by DmitryKvant** [Cuadrix/puppeteer-page-proxy#15]
### log with longjohn
Error: connect ECONNRESET 127.0.0.1:50258
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:855:35)
    at tickOnSocket (_http_client.js:696:10)
    at onSocketNT (_http_client.js:747:5)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:735:11)
    at new ClientRequest (_http_client.js:305:14)
    at request (http.js:46:10)
    at get (http.js:50:15)
    at initAsClient (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/ws/lib/websocket.js:555:31)
    at new WebSocket (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/ws/lib/websocket.js:70:7)
    at Object.get (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer-page-proxy/src/lib/cookies.js:7:20)
    at Page.$puppeteerPageProxyHandler (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer-page-proxy/src/core/page-proxy.js:19:55)
    at Page.emit (events.js:311:20)
    at NetworkManager.<anonymous> (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer/lib/Page.js:110:68)
    at NetworkManager.emit (events.js:323:22)
    at NetworkManager._onRequest (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer/lib/NetworkManager.js:234:10)
    at NetworkManager._onRequestPaused (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer/lib/NetworkManager.js:210:12)
    at CDPSession.emit (events.js:311:20)
    at CDPSession._onMessage (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (/Users/dmitrykvant/Projects/yandexServiceBot/yandexServiceBotPuppeteerV/node_modules/ws/lib/receiver.js:422:14)

**Comment by DmitryKvant** [comment]
Project have last version of agent-base dependencie. But puppeter have not last version. I updated it, not work

**Comment by Cuadrix** [comment]
Try v1.2.4
