### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by kirosc** [Cuadrix/puppeteer-page-proxy#48]
```
(node:6264) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at new CookieHandler (C:\Project\node_modules\puppeteer-page-proxy\src\lib\cookies.js:68:23)
    at requestHandler (C:\Project\node_modules\puppeteer-page-proxy\src\core\proxy.js:12:27)
    at $ppp_request_listener (C:\Project\node_modules\puppeteer-page-proxy\src\core\proxy.js:82:15)
    at C:\Project\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Project\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at Page.emit (C:\Project\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at C:\Project\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:164:100
```
"puppeteer": "^5.3.1",
"puppeteer-page-proxy": "^1.2.8"

**Comment by smartdev10** [comment]
any updates about this i get the same

**Comment by nastycoder** [comment]
So it looks like this problem is caused when an `iframe` element doesn't have a `src` url. 

Unless I'm missing something a simple change [here](https://github.com/Cuadrix/puppeteer-page-proxy/blob/master/src/lib/cookies.js#L68) would resolve the issue and stick to the intended behavior.

```javascript
this.domain = (this.url) ? new URL(this.url).hostname : '';
```

**Comment by 3024407779** [comment]
Do you have a way to set up all page IPs? I need to get all page proxies

**Comment by tgprojet** [comment]
Still facing the same issue, any updates?
