### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by MAkcanca** [Cuadrix/puppeteer-page-proxy#6]
```    
static Target = {
                  ^
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (.\node_modules\puppeteer-page-proxy\src\lib\cookies.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

I'm receiving this error just by importing the library on a simple node.js file. 
Node version v10.16.0

**Comment by Cuadrix** [comment]
Fixed in [v1.2.3](https://github.com/Cuadrix/puppeteer-page-proxy/releases/tag/1.2.3)
