### ISSUE TITLE
Getting error : Request is already handled

### ISSUE THREAD

**Issue by vlourme** [Cuadrix/puppeteer-page-proxy#7]
Hi, I'm getting this error, after testing using `lookup`, it seems the proxy work, I get the good IP I set before, but I always get this error:
```
(node:50589) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at assert (/Users/vico/Development/JS/project/node_modules/puppeteer/lib/helper.js:283:11)
    at Request.abort (/Users/vico/Development/JS/project/node_modules/puppeteer/lib/NetworkManager.js:495:5)
    at Request.<anonymous> (/Users/vico/Development/JS/project/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.$puppeteerPageProxyHandler (/Users/vico/Development/JS/project/node_modules/puppeteer-page-proxy/src/core/page-proxy.js:36:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:50589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 530)
```

**Comment by tingfeng-key** [comment]
@vlourme How do you solve this problem? I also have this problem now
