### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by Hodor228** [Cuadrix/puppeteer-page-proxy#72]
What is wrong?

```
   console.log(`Proxy1: ${proxy}`);
    page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36');

    await useProxy(page, proxy)
```
    
 Output:
 
 Proxy1: socks5://xxxxx:xxxxxx@xxx.xxx.xxx.xx:xxxxx
(node:18228) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of undefined
    at useProxy (C:\Users\admin\Desktop\script\node_modules\puppeteer-page-proxy\src\core\proxy.js:90:31)
    at Main (C:\Users\admin\Desktop\script\main2.0.js:494:11)

**Comment by Hodor228** [comment]
It was fixed by latest version your plugin and puppeteer
