### ISSUE TITLE
Error: new SocksProxyAgent(proxy)

### ISSUE THREAD

**Issue by charlesbao** [Cuadrix/puppeteer-page-proxy#85]
node v16.15.0
puppeteer 19.0.0
puppeteer-page-proxy 1.2.9
socks-proxy-agent 7.0.0

/xxx/node_modules/puppeteer-page-proxy/src/lib/options.js:29
            http: new SocksProxyAgent(proxy),
                  ^

TypeError: SocksProxyAgent is not a constructor
    at setAgent (/xxx/node_modules/puppeteer-page-proxy/src/lib/options.js:29:19)
    at requestHandler (/xxx/node_modules/puppeteer-page-proxy/src/core/proxy.js:19:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $ppp_requestListener (/xxx/node_modules/puppeteer-page-proxy/src/core/proxy.js:83:13)
    at async HTTPRequest.finalizeInterceptions (/xxx/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:188:9)

**Comment by Cuadrix** [comment]
https://github.com/Cuadrix/puppeteer-page-proxy/releases/tag/1.3.0
