### ISSUE TITLE
type error error when using socks proxy with authentication

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [Cuadrix/puppeteer-page-proxy#86]
Waiting for the debugger to disconnect...
C:\Users\pc\projects\rs-account-creator\node_modules\puppeteer-page-proxy\src\lib\options.js:29
            http: new SocksProxyAgent(proxy),
                  ^

TypeError: SocksProxyAgent is not a constructor
    at setAgent (C:\Users\pc\projects\rs-account-creator\node_modules\puppeteer-page-proxy\src\lib\options.js:29:19)
    at requestHandler (C:\Users\pc\projects\rs-account-creator\node_modules\puppeteer-page-proxy\src\core\proxy.js:19:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $ppp_requestListener (C:\Users\pc\projects\rs-account-creator\node_modules\puppeteer-page-proxy\src\core\proxy.js:83:13)
    at async HTTPRequest.finalizeInterceptions (C:\Users\pc\projects\rs-account-creator\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPRequest.js:188:9)

Node.js v18.11.0
Waiting for the debugger to disconnect...

**Comment by Cuadrix** [comment]
https://github.com/Cuadrix/puppeteer-page-proxy/releases/tag/1.3.0
